# Generated by Django 3.2.16 on 2023-04-19 12:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main_app.models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_priority', models.IntegerField(default=50, verbose_name='Category priority')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Geolocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Geolocation',
                'verbose_name_plural': 'Geolocations',
                'db_table': 'geolocations',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_in_stories', models.BooleanField(default=False, verbose_name='Hide in stories')),
                ('post_priority', models.IntegerField(default=20, verbose_name='Post priority')),
                ('fresh_after', models.DateField(blank=True, null=True, verbose_name='Fresh after')),
                ('fresh_before', models.DateField(blank=True, null=True, verbose_name='Fresh before')),
                ('clients_eligible', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=main_app.models.get_default_clients, null=True, size=None)),
                ('geolocations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=main_app.models.get_default_geolocations, null=True, size=None)),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stories_categories', to='main_app.categories', verbose_name='Category id')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'db_table': 'stories',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Stories_i18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', mdeditor.fields.MDTextField(verbose_name='Title')),
                ('subtitle', mdeditor.fields.MDTextField(verbose_name='Subtitle')),
                ('title_icon', models.ImageField(storage=main_app.models.MyOwnStorage(), upload_to=main_app.models.content_file_name_title_icon, verbose_name='Title icon')),
                ('title_image', models.ImageField(storage=main_app.models.MyOwnStorage(), upload_to=main_app.models.content_file_name_title_image, verbose_name='Title image')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.languages', verbose_name='Language id')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storiesi18n_stories', to='main_app.stories', verbose_name='Story id')),
            ],
            options={
                'verbose_name': 'Story_i18n',
                'verbose_name_plural': 'Stories_i18n',
                'db_table': 'stories_i18n',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Categories_i18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='News', max_length=500, verbose_name='Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoriesi18n_categories', to='main_app.categories', verbose_name='Category id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.languages', verbose_name='Language id')),
            ],
            options={
                'verbose_name': 'Category_i18n',
                'verbose_name_plural': 'Categories_i18n',
                'db_table': 'categories_i18n',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=main_app.models.MyOwnStorage(), upload_to=main_app.models.content_file_name_image, verbose_name='Image')),
                ('icon', models.ImageField(default='assets/icon/icon_startscreen_new.svg', storage=main_app.models.MyOwnStorage(), upload_to=main_app.models.content_file_name_icon, verbose_name='Icon')),
                ('headline', mdeditor.fields.MDTextField(verbose_name='Headline')),
                ('text', mdeditor.fields.MDTextField(verbose_name='Text')),
                ('mark_deleted', models.BooleanField(default=False, verbose_name='Mark deleted')),
                ('order', models.IntegerField(default=100, verbose_name='Order')),
                ('story_i18n', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages_storiesi18n', to='main_app.stories_i18n', verbose_name='Story_i18n id')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['order'],
                'unique_together': {('story_i18n', 'order')},
            },
        ),
    ]
